// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendDollars.Data;

#nullable disable

namespace SpendDollars.Migrations
{
    [DbContext(typeof(MoneyDbContext))]
    [Migration("20220604175145_ThirdMig")]
    partial class ThirdMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("SpendDollars.Models.MoneySpent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Donate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EatOut")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Education")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Entertainment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hobby")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Party")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Personal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shopping")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Spa")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Vacation")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("MoneySpent");
                });
#pragma warning restore 612, 618
        }
    }
}
