// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendDollars.Data;

#nullable disable

namespace SpendDollars.Migrations
{
    [DbContext(typeof(MoneyDbContext))]
    [Migration("20220616194617_Fifth")]
    partial class Fifth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("SpendDollars.Models.MoneySpent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Donate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EatOut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Education")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Entertainment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hobby")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Party")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Personal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shopping")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vacation")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("MoneySpent");
                });
#pragma warning restore 612, 618
        }
    }
}
